/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginAuthLoginPostGrantType } from "./body-login-auth-login-post-grant-type";
import type { BodyLoginAuthLoginPostClientId } from "./body-login-auth-login-post-client-id";
import type { BodyLoginAuthLoginPostClientSecret } from "./body-login-auth-login-post-client-secret";

export interface BodyLoginAuthLoginPost {
  grant_type?: BodyLoginAuthLoginPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginAuthLoginPostClientId;
  client_secret?: BodyLoginAuthLoginPostClientSecret;
}
