/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginAuthLoginPostGrantType } from "./bodyLoginAuthLoginPostGrantType";
import type { BodyLoginAuthLoginPostClientId } from "./bodyLoginAuthLoginPostClientId";
import type { BodyLoginAuthLoginPostClientSecret } from "./bodyLoginAuthLoginPostClientSecret";

export interface BodyLoginAuthLoginPost {
  grant_type?: BodyLoginAuthLoginPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginAuthLoginPostClientId;
  client_secret?: BodyLoginAuthLoginPostClientSecret;
}
