/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Gender } from "./gender";

export interface UserResponse {
  user_id: number;
  user_age: number;
  user_gender: Gender;
  user_email: string;
  user_username: string;
}
