/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Gender } from "./gender";

export interface UserCreate {
  user_gender: Gender;
  /** @minLength 3 */
  user_username: string;
  /** @minLength 8 */
  user_password: string;
  user_email: string;
  /**
   * @minimum 16
   * @maximum 80
   */
  user_age: number;
}
