/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserWithToken {
  user_id: number;
  user_username: string;
  user_email: string;
  access_token: string;
  token_type: string;
}
